version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../backend/data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production

volumes:
  frontend_build: 