# Frontend Dockerfile
FROM node:18-alpine as build

WORKDIR /app

COPY chatUI/package*.json ./
COPY docker/.env .
RUN npm install --registry=https://registry.npmmirror.com
RUN npm install dotenv-cli --registry=https://registry.npmmirror.com

COPY chatUI .
RUN npx dotenv -e .env npm run build

# Copy build artifacts to shared volume
FROM alpine:latest
RUN mkdir -p /app/dist
COPY --from=build /app/dist /app/dist
VOLUME /app/dist